version: '3.4'

services:
  contactdb:
    image: mongo

  contact.api:
    image: ${DOCKER_REGISTRY-}contactapi
    build:
      context: .
      dockerfile: Contact.API/Dockerfile

volumes:
  mongo_data: