version: '3.4'

services:
  contactdb:
    image: mongo

  reportdb:
    image: redis:alpine
    
  rabbitmq:
    image: rabbitmq:3-management-alpine

  contact.api:
    image: ${DOCKER_REGISTRY-}contactapi
    build:
      context: .
      dockerfile: Contact.API/Dockerfile

  report.api:
    image: ${DOCKER_REGISTRY-}reportapi
    build:
      context: .
      dockerfile: Report.API/Dockerfile

  ocelotapi:
    image: ${DOCKER_REGISTRY-}ocelotapi
    build:
      context: .
      dockerfile: OcelotApi/Dockerfile

volumes:
  mongo_data:

